/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MKL02Z32xxx4
package_id: MKL02Z32VFG4
mcu_data: ksdk2_0
processor_version: 4.0.0
pin_labels:
- {pin_num: '5', pin_signal: PTA5/TPM0_CH1/SPI0_SS_b, label: POWERSW, identifier: POWERSW}
- {pin_num: '4', pin_signal: XTAL0/PTA4/I2C0_SDA/I2C1_SCL, label: ENABLE, identifier: ENABLE}
- {pin_num: '6', pin_signal: PTA6/TPM0_CH0/SPI0_MISO, label: BLUELED, identifier: BLUELED}
- {pin_num: '7', pin_signal: ADC0_SE7/PTA7/IRQ_4/SPI0_MISO/SPI0_MOSI, label: REDLED, identifier: REDLED}
- {pin_num: '3', pin_signal: EXTAL0/PTA3/I2C0_SCL/I2C1_SDA, label: A3, identifier: A3}
- {pin_num: '8', pin_signal: ADC0_SE6/PTB0/IRQ_5/EXTRG_IN/SPI0_SCK, label: B0, identifier: B0}
- {pin_num: '9', pin_signal: ADC0_SE5/CMP0_IN3/PTB1/IRQ_6/UART0_TX/UART0_RX, label: B1, identifier: B1}
- {pin_num: '10', pin_signal: ADC0_SE4/PTB2/IRQ_7/UART0_RX/UART0_TX, label: B2, identifier: B2}
- {pin_num: '11', pin_signal: PTB3/IRQ_10/I2C0_SCL/UART0_TX, label: B3, identifier: B3}
- {pin_num: '12', pin_signal: PTB4/IRQ_11/I2C0_SDA/UART0_RX, label: B4, identifier: B4}
- {pin_num: '13', pin_signal: ADC0_SE1/CMP0_IN1/PTB5/IRQ_12/TPM1_CH1/NMI_b, label: B5, identifier: B5}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: GPIOA, signal: 'GPIO, 3', pin_signal: EXTAL0/PTA3/I2C0_SCL/I2C1_SDA, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIOA, signal: 'GPIO, 4', pin_signal: XTAL0/PTA4/I2C0_SDA/I2C1_SCL, direction: INPUT, pull_enable: enable}
  - {pin_num: '5', peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: PTA5/TPM0_CH1/SPI0_SS_b, direction: OUTPUT, gpio_init_state: 'true', open_drain: disable}
  - {pin_num: '6', peripheral: GPIOA, signal: 'GPIO, 6', pin_signal: PTA6/TPM0_CH0/SPI0_MISO, direction: INPUT}
  - {pin_num: '7', peripheral: GPIOA, signal: 'GPIO, 7', pin_signal: ADC0_SE7/PTA7/IRQ_4/SPI0_MISO/SPI0_MOSI, direction: INPUT}
  - {pin_num: '8', peripheral: GPIOB, signal: 'GPIO, 0', pin_signal: ADC0_SE6/PTB0/IRQ_5/EXTRG_IN/SPI0_SCK, direction: OUTPUT}
  - {pin_num: '9', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE5/CMP0_IN3/PTB1/IRQ_6/UART0_TX/UART0_RX, direction: OUTPUT}
  - {pin_num: '10', peripheral: GPIOB, signal: 'GPIO, 2', pin_signal: ADC0_SE4/PTB2/IRQ_7/UART0_RX/UART0_TX, direction: OUTPUT}
  - {pin_num: '11', peripheral: GPIOB, signal: 'GPIO, 3', pin_signal: PTB3/IRQ_10/I2C0_SCL/UART0_TX, direction: OUTPUT}
  - {pin_num: '12', peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: PTB4/IRQ_11/I2C0_SDA/UART0_RX, direction: OUTPUT}
  - {pin_num: '13', peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: ADC0_SE1/CMP0_IN1/PTB5/IRQ_12/TPM1_CH1/NMI_b, direction: OUTPUT}
  - {pin_num: '14', peripheral: SWD, signal: SWD_CLK, pin_signal: ADC0_SE12/CMP0_IN2/PTA0/IRQ_0/TPM1_CH0/SWD_CLK}
  - {pin_num: '16', peripheral: SWD, signal: SWD_DIO, pin_signal: PTA2/CMP0_OUT/SWD_DIO}
  - {pin_num: '15', peripheral: RCM, signal: RESET, pin_signal: PTA1/IRQ_1/LPTMR0_ALT1/TPM_CLKIN0/RESET_b}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);

    gpio_pin_config_t A3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA3 (pin 3)  */
    GPIO_PinInit(BOARD_INITPINS_A3_GPIO, BOARD_INITPINS_A3_PIN, &A3_config);

    gpio_pin_config_t ENABLE_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA4 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_ENABLE_GPIO, BOARD_INITPINS_ENABLE_PIN, &ENABLE_config);

    gpio_pin_config_t POWERSW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U
    };
    /* Initialize GPIO functionality on pin PTA5 (pin 5)  */
    GPIO_PinInit(BOARD_INITPINS_POWERSW_GPIO, BOARD_INITPINS_POWERSW_PIN, &POWERSW_config);

    gpio_pin_config_t BLUELED_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA6 (pin 6)  */
    GPIO_PinInit(BOARD_INITPINS_BLUELED_GPIO, BOARD_INITPINS_BLUELED_PIN, &BLUELED_config);

    gpio_pin_config_t REDLED_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA7 (pin 7)  */
    GPIO_PinInit(BOARD_INITPINS_REDLED_GPIO, BOARD_INITPINS_REDLED_PIN, &REDLED_config);

    gpio_pin_config_t B0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB0 (pin 8)  */
    GPIO_PinInit(BOARD_INITPINS_B0_GPIO, BOARD_INITPINS_B0_PIN, &B0_config);

    gpio_pin_config_t B1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB1 (pin 9)  */
    GPIO_PinInit(BOARD_INITPINS_B1_GPIO, BOARD_INITPINS_B1_PIN, &B1_config);

    gpio_pin_config_t B2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB2 (pin 10)  */
    GPIO_PinInit(BOARD_INITPINS_B2_GPIO, BOARD_INITPINS_B2_PIN, &B2_config);

    gpio_pin_config_t B3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB3 (pin 11)  */
    GPIO_PinInit(BOARD_INITPINS_B3_GPIO, BOARD_INITPINS_B3_PIN, &B3_config);

    gpio_pin_config_t B4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB4 (pin 12)  */
    GPIO_PinInit(BOARD_INITPINS_B4_GPIO, BOARD_INITPINS_B4_PIN, &B4_config);

    gpio_pin_config_t B5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB5 (pin 13)  */
    GPIO_PinInit(BOARD_INITPINS_B5_GPIO, BOARD_INITPINS_B5_PIN, &B5_config);

    /* PORTA0 (pin 14) is configured as SWD_CLK */
    PORT_SetPinMux(PORTA, 0U, kPORT_MuxAlt3);

    /* PORTA1 (pin 15) is configured as RESET_b */
    PORT_SetPinMux(PORTA, 1U, kPORT_MuxAlt3);

    /* PORTA2 (pin 16) is configured as SWD_DIO */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt3);

    /* PORTA3 (pin 3) is configured as PTA3 */
    PORT_SetPinMux(BOARD_INITPINS_A3_PORT, BOARD_INITPINS_A3_PIN, kPORT_MuxAsGpio);

    const port_pin_config_t ENABLE = {/* Internal pull-up resistor is enabled */
                                      kPORT_PullUp,
                                      /* Passive filter is disabled */
                                      kPORT_PassiveFilterDisable,
                                      /* Low drive strength is configured */
                                      kPORT_LowDriveStrength,
                                      /* Pin is configured as PTA4 */
                                      kPORT_MuxAsGpio};
    /* PORTA4 (pin 4) is configured as PTA4 */
    PORT_SetPinConfig(BOARD_INITPINS_ENABLE_PORT, BOARD_INITPINS_ENABLE_PIN, &ENABLE);

    /* PORTA5 (pin 5) is configured as PTA5 */
    PORT_SetPinMux(BOARD_INITPINS_POWERSW_PORT, BOARD_INITPINS_POWERSW_PIN, kPORT_MuxAsGpio);

    /* PORTA6 (pin 6) is configured as PTA6 */
    PORT_SetPinMux(BOARD_INITPINS_BLUELED_PORT, BOARD_INITPINS_BLUELED_PIN, kPORT_MuxAsGpio);

    /* PORTA7 (pin 7) is configured as PTA7 */
    PORT_SetPinMux(BOARD_INITPINS_REDLED_PORT, BOARD_INITPINS_REDLED_PIN, kPORT_MuxAsGpio);

    /* PORTB0 (pin 8) is configured as PTB0 */
    PORT_SetPinMux(BOARD_INITPINS_B0_PORT, BOARD_INITPINS_B0_PIN, kPORT_MuxAsGpio);

    /* PORTB1 (pin 9) is configured as PTB1 */
    PORT_SetPinMux(BOARD_INITPINS_B1_PORT, BOARD_INITPINS_B1_PIN, kPORT_MuxAsGpio);

    /* PORTB2 (pin 10) is configured as PTB2 */
    PORT_SetPinMux(BOARD_INITPINS_B2_PORT, BOARD_INITPINS_B2_PIN, kPORT_MuxAsGpio);

    /* PORTB3 (pin 11) is configured as PTB3 */
    PORT_SetPinMux(BOARD_INITPINS_B3_PORT, BOARD_INITPINS_B3_PIN, kPORT_MuxAsGpio);

    /* PORTB4 (pin 12) is configured as PTB4 */
    PORT_SetPinMux(BOARD_INITPINS_B4_PORT, BOARD_INITPINS_B4_PIN, kPORT_MuxAsGpio);

    /* PORTB5 (pin 13) is configured as PTB5 */
    PORT_SetPinMux(BOARD_INITPINS_B5_PORT, BOARD_INITPINS_B5_PIN, kPORT_MuxAsGpio);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
