/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTA3 (number 3), A3
  @{ */
#define BOARD_INITPINS_A3_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_A3_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_A3_PIN 3U     /*!<@brief PORTA pin index: 3 */
                                     /* @} */

/*! @name PORTA4 (number 4), ENABLE
  @{ */
#define BOARD_INITPINS_ENABLE_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_ENABLE_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_ENABLE_PIN 4U     /*!<@brief PORTA pin index: 4 */
                                         /* @} */

/*! @name PORTA5 (number 5), POWERSW
  @{ */
#define BOARD_INITPINS_POWERSW_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_POWERSW_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_POWERSW_PIN 5U     /*!<@brief PORTA pin index: 5 */
                                          /* @} */

/*! @name PORTA6 (number 6), BLUELED
  @{ */
#define BOARD_INITPINS_BLUELED_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_BLUELED_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_BLUELED_PIN 6U     /*!<@brief PORTA pin index: 6 */
                                          /* @} */

/*! @name PORTA7 (number 7), REDLED
  @{ */
#define BOARD_INITPINS_REDLED_GPIO GPIOA /*!<@brief GPIO device name: GPIOA */
#define BOARD_INITPINS_REDLED_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_REDLED_PIN 7U     /*!<@brief PORTA pin index: 7 */
                                         /* @} */

/*! @name PORTB0 (number 8), B0
  @{ */
#define BOARD_INITPINS_B0_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_B0_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_B0_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                     /* @} */

/*! @name PORTB1 (number 9), B1
  @{ */
#define BOARD_INITPINS_B1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_B1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_B1_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                     /* @} */

/*! @name PORTB2 (number 10), B2
  @{ */
#define BOARD_INITPINS_B2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_B2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_B2_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                     /* @} */

/*! @name PORTB3 (number 11), B3
  @{ */
#define BOARD_INITPINS_B3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_B3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_B3_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                     /* @} */

/*! @name PORTB4 (number 12), B4
  @{ */
#define BOARD_INITPINS_B4_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_B4_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_B4_PIN 4U     /*!<@brief PORTB pin index: 4 */
                                     /* @} */

/*! @name PORTB5 (number 13), B5
  @{ */
#define BOARD_INITPINS_B5_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_B5_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_B5_PIN 5U     /*!<@brief PORTB pin index: 5 */
                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
